Repository nmshd/connector-school-module, pull requests merged in 2025-04, with the labels that each got.

#23 Add DELETE route and do not delete students automatically (but remove all personal data)
  .env.connector
  Taskfile.yml
  package-lock.json
  package.json
  src/StudentsController.ts
  src/controllers/StudentsRESTController.ts
  src/index.ts
  src/types/Student.ts
  src/types/StudentDTO.ts
Labels: enhancement

#24 Send Mail Routes
  .gitignore
  config.json
  package-lock.json
  package.json
  src/StudentsController.ts
  src/controllers/StudentsRESTController.ts
  src/controllers/schemas.ts
  src/index.ts
Labels: enhancement

#25 Fix relationship template deletion, title of files, tags of certificate
  .gitignore
  assets/mail_offboarding.txt
  assets/mail_onboarding.txt
  assets/template_onboarding.pdf
  config.json
  src/StudentsController.ts
  src/controllers/StudentsRESTController.ts
  src/index.ts
Labels: bug, enhancement

#27 Switch to TransferFileOwnershipRequestItem
  src/StudentsController.ts
Labels: enhancement

#28 Enable more file tags
  .ci/buildAndPush.sh
  .env.connector
  package-lock.json
  package.json
  src/controllers/StudentsRESTController.ts
Labels: enhancement

#29 Add excel file with module specific configuration
  Connectors.xlsx
Labels: chore

#30 Increase column width in excel template
  Connectors.xlsx
Labels: chore

#32 Mail placeholders are not filled from request body
  src/controllers/StudentsRESTController.ts
Labels: bug

#33 Add repo to package.json
  package.json
Labels: chore

#34 Title from additional consents is never used
  Taskfile.yml
  src/StudentsController.ts
  src/controllers/schemas.ts
Labels: bug

#36 Add linkDisplayText to consents
  src/StudentsController.ts
  src/controllers/schemas.ts
Labels: enhancement

#37 Bump connector
  .env.connector
  package-lock.json
  package.json
Labels: dependencies

#38 Deleting an inactive student is not possible if autoMailBeforeOffboarding is turned on
  src/StudentsController.ts
Labels: bug

#39 Make debuggable
  .github/workflows/publish.yml
  .vscode/launch.json
  compose.yaml
  package.json
  tsconfig.json
  tsconfig.prod.json
Labels: chore

#40 App store links in pdfs
  Connectors.xlsx
  config.json
  src/StudentsController.ts
  src/index.ts
Labels: enhancement

#43 Use passwordLocationIndicator to specify the password location
  .env.connector
  .github/release.yml
  package-lock.json
  package.json
  src/StudentsController.ts
Labels: enhancement

#44 UTF-8 Characters break PDF Templating without a proper error message
  src/StudentsController.ts
Labels: bug
