Repository nmshd/connector-school-module, pull requests merged in 2025-05, with the labels that each got.

#45 Student Audit Log
  src/StudentsController.ts
  src/controllers/StudentsRESTController.ts
  src/types/StudentDTO.ts
Labels: bug, enhancement

#46 Bump connector
  .env.connector
  .vscode/tasks.json
  package-lock.json
  package.json
Labels: dependencies

#47 Move student audit log
  src/types/StudentAuditLog.ts
  src/types/StudentDTO.ts
  src/types/index.ts
Labels: refactoring

#49 The verbose query parameter is not handled properly
  Taskfile.yml
  src/controllers/StudentsRESTController.ts
Labels: bug

#50 Names are cut in the default onboarding template
  assets/template_onboarding.pdf
Labels: bug

#51 Add support for url references
  .env.connector
  config.json
  package-lock.json
  package.json
  src/StudentsController.ts
  src/index.ts
Labels: enhancement

#52 Bump connector
  .env.connector
  package-lock.json
  package.json
Labels: dependencies

#53 Make reference url format the default for the rendered QR code
  Connectors.xlsx
  Taskfile.yml
  assets/template_onboarding.pdf
  config.json
  src/StudentsController.ts
  src/index.ts
Labels: enhancement

#56 Remove requireManualDecision from TransferFileOwnershipRequestItem
  src/StudentsController.ts
Labels: bug

#57 Allow jpg for school logos
  src/StudentsController.ts
Labels: enhancement

#60 Wording
  src/StudentsController.ts
Labels: chore

#61 Make the pdf generation fully customizable
  .env.connector
  Taskfile.yml
  assets/template_onboarding.pdf
  package-lock.json
  package.json
  src/StudentsController.ts
  src/controllers/StudentsRESTController.ts
  src/controllers/schemas.ts
  src/types/PDFSettings.ts
  src/types/index.ts
Labels: enhancement

#62 additionalConsents validation is incorrect
  src/StudentsController.ts
  src/controllers/schemas.ts
Labels: bug

#63 Bump connector
  .env.connector
  package-lock.json
  package.json
Labels: dependencies
